/** 電卓ボタンの値一覧 */
export const Value = Object.freeze({
    ONE:            '1',
    TWO:            '2',
    THREE:          '3',
    FOUR:           '4',
    FIVE:           '5',
    SIX:            '6',
    SEVEN:          '7',
    EIGHT:          '8',
    NINE:           '9',
    ZERO:           '0',

    PLUS:           '+',
    MINUS:          '-',
    MULTIPLY:       '*',
    DIVIDE:         '/',

    EQUAL:          '=',
    CLEAR:          'C',

    // DOT:            '.',
    // PERCENT:        '%',
    // NEGATIVE:       '+/-',
    // BACKSPACE:      '←',
    // SQUARE:         'x²',
    // SQUARE_ROOT:    '√',
    // ONE_DIVIDE:     '1/x',
    // SIN:            'sin',
    // COS:            'cos',
    // TAN:            'tan',
    // LOG:            'log',
    // LN:             'ln',
    // PI:             'π',
    // E:              'e',
    // EXP:            'exp',
    // OPEN_PAREN:     '(',
    // CLOSE_PAREN:    ')',
    // MEMORY_CLEAR:   'MC',
    // MEMORY_READ:    'MR',
    // MEMORY_PLUS:    'M+',
    // MEMORY_MINUS:   'M-',
})